# Generated by Django 4.0.3 on 2022-12-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRestApp', '0002_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=400)),
                ('ticket_func', models.CharField(max_length=10000)),
                ('ticket_image', models.URLField(max_length=500)),
            ],
        ),
    ]
