# Generated by Django 4.0.3 on 2022-12-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRestApp', '0004_alter_ticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_image',
            new_name='ticket_img',
        ),
    ]
