# Generated by Django 4.0.3 on 2022-12-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRestApp', '0005_rename_ticket_image_ticket_ticket_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_img',
            new_name='ticket_image',
        ),
    ]
