# Generated by Django 4.0.3 on 2022-12-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRestApp', '0006_rename_ticket_img_ticket_ticket_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='userHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoRestApp.ticket')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoRestApp.user')),
            ],
        ),
    ]
