# Generated by Django 4.0.3 on 2022-12-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRestApp', '0009_alter_userhistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
